theme: cayman
plugins: 
  - jekyll-sass-converter
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-titles-from-headings
  - kramdown
  - liquid  

collections:
  phish:
    output: true
  edu:
    output: true
  learn: 
    output: true
  misc:
    output: true
collections_dir: my_collections
