theme: jekyll-theme-cayman
plugins: 
  - jekyll-sass-converter
  - jekyll-seo-tag
  - jekyll-sitemap
  
collections:
  phish:
    output: true
  edu:
    output: true
  learn: 
    output: true
  misc:
    output: true
